version: '3.8'

services:
  # Backend API service
  backend:
    build: ./backend
    container_name: legal-rag-backend
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/vector_db:/app/vector_db
      - ./backend/metadata:/app/metadata
    env_file:
      - ./backend/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - legal-rag-network

  # Frontend service
  frontend:
    build: ./frontend
    container_name: legal-rag-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - legal-rag-network

networks:
  legal-rag-network:
    driver: bridge
