site_name: Legal Domain RAG System
site_description: Documentation for the Legal Domain Retrieval-Augmented Generation System
site_author: Developer
copyright: "&copy; 2023"

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Document Management: user-guide/document-management.md
      - Querying Documents: user-guide/querying.md
      - Administration: user-guide/administration.md
  - API Reference:
      - Overview: api/overview.md
      - Document API: api/documents.md
      - Query API: api/queries.md
      - Admin API: api/admin.md
  - Development:
      - Architecture: dev/architecture.md
      - Environment Setup: dev/environment.md
      - Backend Development: dev/backend.md
      - Frontend Development: dev/frontend.md
      - Testing: dev/testing.md
      - Deployment: dev/deployment.md
  - Technical Details:
      - ChromaDB Integration: technical/chromadb.md
      - Google Gemini Integration: technical/gemini.md
      - Embedding Models: technical/embeddings.md
      - Document Processing: technical/document-processing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("backend")
          selection:
            members: true
          rendering:
            show_source: true
  - swagger-ui-tag:
      openapi_file: backend/openapi.json
